### ISSUE TITLE
[Enhancement Request] - Few 

### ISSUE THREAD

**Issue by RahulMR42** [oracle-devrel/terraform-oci-arch-devops-cicd-oke-helm#8]
Very intersting RA - thank you for that ,could you update these also in the readme 

- how to test the application (where will they get the public IP and what do with that) 
- Before the deletion also warn customer to delete the loadbalancer by the helm deployment to clean ,else the stack or terraform destroy will fail 

- You may refer to oci-devops-samples too from a link from Readme

**Comment by lfeldman** [comment]
@RahulMR42 would you be so kind to provide Pull Request with the README update?

**Comment by RahulMR42** [comment]
@lfeldman  - its here #9

**Comment by lfeldman** [comment]
Now looks like the work is done. :) Closing ticket. :)
